export { default as About } from './About'
export { default as Dashboard } from './Dashboard'
export { default as Home } from './Home'
export { default as Landing } from './Landing'
export { default as News } from './News'
export { default as NotFound } from './NotFound'